version: 2.1
jobs:
  build:
    docker:
      - image: yisoda/texlive-full-simple:_test
    steps:
      - checkout
      - run:
          command: |
            apt update
            curl -O https://github.com/jgm/pandoc/releases/download/2.8.0.1/pandoc-2.8.0.1-1-amd64.deb
            dpkg -i pandoc-2.8.0.1-1-amd64.deb
            apt install -y ca-certificates
            apt install -y texlive-fonts-recommended texlive-fonts-extra fonts-texgyre
      - run:
          command: pandoc --standalone --to=latex+header_attributes+auto_identifiers+superscript+footnotes+inline_notes --number-sections --output=Density-Operator.tex Density-Operator.md
          # working_directory: paper
      - run:
          command: lualatex Density-Operator.tex
      - store_artifacts:
          path: Density-Operator.tex
      - store_artifacts:
          path: Density-Operator.pdf

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - pdf
