version: 2.1
jobs:
  build:
    docker:
      - image: yisoda/texlive-full-simple:_test
    steps:
      - checkout
      - run:
          command: |
            apt update
            apt install -y pandoc
            apt install -y ca-certificates
      - run:
          command: pandoc --standalone --to=latex+header_attributes+auto_identifiers+superscript+footnotes+inline_notes --number-sections --output=Density-Operator.tex Density-Operator.md
          # working_directory: paper
      - run:
          command: cluttex -e lualatex --max-iterations 1 Density-Operator.tex
      - store_artifacts:
          path: Density-Operator.tex
      - store_artifacts:
          path: Density-Operator.pdf

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - pdf
